### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PyCharm

### POST -> Register User
POST localhost:3030/api/auth/register
Content-Type: application/json

{
"name": "lelei gideon",
  "email": "lelei10@gmail.com",
  "password": "12345678"
}


### POST -> Login User
POST localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "lelei10@gmail.com",
  "password": "12345678"
}

### POST -> Login User
POST localhost:3030/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjExMjQzNywianRpIjoiMDNhYTVmZTEtN2ExZi00MDUyLWEzMWYtYmFkNGM0NmI3MWNhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NzYxMTI0MzcsImNzcmYiOiJjODIwYmI1ZC0zOGFhLTRmMTQtYWI1My1kNDYwNmRjYjM3YWYiLCJleHAiOjE3NzYxMTYwMzd9.xSDvtS_pm0210vGUmNs7xVmgY-Dz7eZukTtvqusYvyk

### POST -> Login User
GET localhost:3030/api/auth/validate-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjExMjg5MiwianRpIjoiNzAxMzVmZTEtZjQ3Ny00OTE3LTk0OGUtNmU0Mzk1NjA3M2ZkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NzYxMTI4OTIsImNzcmYiOiI3YTVkNTQ0OC0wOTI2LTRhOWItODNhOC04NjRmMDYxYTczNGMiLCJleHAiOjE3NzYxMTY0OTJ9.OZuU9iQp9-YY68Hwcj5tHGq3U5Z7yaVxvW6nkDZErcE

### POST -> Create Todo
POST localhost:3030/api/todos
Content-Type: application/json
Authorization: access_token_cookie eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjE0NjcyMiwianRpIjoiMWI3MmU0MmYtYzJlOS00ZmQ3LTlkN2MtNDEzNDkzY2UyMjA2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NzYxNDY3MjIsImV4cCI6MTc3NjE1MDMyMn0.GJLQ7OD1E0s7L9XEu4uMGdvAtATiv5e7q69RCO9guVY

{
  "title": "Create a res api",
  "description": "des",
  "status": "Pending"
}

### GET -> GET A USERS Todo LIST
GET localhost:3030/api/todos
Content-Type: application/json
Authorization: access_token_cookie eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjE0NjcyMiwianRpIjoiMWI3MmU0MmYtYzJlOS00ZmQ3LTlkN2MtNDEzNDkzY2UyMjA2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjIiLCJuYmYiOjE3NzYxNDY3MjIsImV4cCI6MTc3NjE1MDMyMn0.GJLQ7OD1E0s7L9XEu4uMGdvAtATiv5e7q69RCO9guVY


### GET -> DELETE A USERS Todo
DELETE localhost:3030/api/todos/1
Content-Type: application/json
Authorization: access_token_cookie eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjE0NzkwNiwianRpIjoiMjE4YzFmMGQtNzdlYi00YWQzLWI3Y2ItYTI1MTc2ZmNiOTEyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjMiLCJuYmYiOjE3NzYxNDc5MDYsImV4cCI6MTc3NjE1MTUwNn0.5NbjHt9WshEUoq9GHUty5ZNQ3GqSllWd_Fw57v4opRA

### GET -> UPDATE A USERS Todo
DELETE localhost:3030/api/todos/1
Content-Type: application/json
Authorization: access_token_cookie eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjE0NzkwNiwianRpIjoiMjE4YzFmMGQtNzdlYi00YWQzLWI3Y2ItYTI1MTc2ZmNiOTEyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjMiLCJuYmYiOjE3NzYxNDc5MDYsImV4cCI6MTc3NjE1MTUwNn0.5NbjHt9WshEUoq9GHUty5ZNQ3GqSllWd_Fw57v4opRA