"""token_black_list

Revision ID: 29d3886603d8
Revises: fc0951bb6a72
Create Date: 2026-04-13 23:10:52.730341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d3886603d8'
down_revision = 'fc0951bb6a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_tokens_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
